---
# this comment is also a hack
version: '3'
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - PASSWORD=Uid5N5iAGloDFoAzsZZE5UGGcXtDhT5r1Tcm7YgC
      - SUDO_PASSWORD=Uid5N5iAGloDFoAzsZZE5UGGcXtDhT5r1Tcm7YgC
    volumes:
      - /docker/docker-compose/vscode/config:/config:Z
    ports:
      - 8443:8443
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
